### PR TITLE
Overclocking instructions in README

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by 4ndr3w — APPROVED** [review]
Looks good.

Might also be worth mentioning the default locations for popular platforms, since the location of the hardware folder really isn't standardized.

**Comment by ghost** [comment]
Fair enough. I know it's typically `/usr/share/arduino/hardware...` or `/opt/arduino/hardware...` for Linux, or in your home directory `/home/<user>/<wherever-arduino-installation-is>/hardware...`. What about Windows and Mac?

I think for @asaba96 on Mac it was `<wherever-arduino-installation-was>/lib/hardware...`

I think it's `<wherever-arduino-installation-is>/hardware` on Windows as well, but not sure.

Can Mac and Windows users post here exactly where your Arduino hardware folders are?

**Comment by 4ndr3w** [comment]
On OS X it's `/Applications/Arduino.app/Contents/Java/hardware...` which I thought was slightly confusing at first

**Comment by ghost** [comment]
Yup that's strange where it is on Mac.

Updated with typical paths.

**Pull request merged**
