### PR TITLE
Delete files

### PR DESCRIPTION
**Pull request by ghost**
Cleanup. No code changes.

### CODE REVIEW

**Comment by ghost** [comment]
Is there any reason we needed `plots/fitter.nb`? 0cf744bf19c5c7bdc0e6f002ce60cf98e243ae10

Otherwise, I don't feel bad about deleting these legacy files since they'll be in the history. But I think we're done with them.

**Comment by amiller27** [comment]
Nah, but we do need the Matlab script.  I started porting it to python a while ago, but never finished.  I'll see if I can clean it up and make a PR in the near future

**Comment by ghost** [comment]
Whoops. That must be how we're getting the `conf.h` swept turn parameters?

**Comment by amiller27** [comment]
yeppers

**Review by amiller27 — APPROVED** [review]

**Pull request merged**
