### PR TITLE
Fixed ContinuousRobotDriver taking wrong default direction

### PR DESCRIPTION
**Pull request by amiller27**
This has been tested on the mouse, fixed the bug @asaba96 was talking about yesterday

### CODE REVIEW

**Comment by ghost** [comment]
Tested in this maze.

test_case

RUN works fine. KAOS does not.

Observed behavior:
  1. Kaoses to the finish.
  2. Remains facing west.
  3. Plays finish melody.
  4. Turns south.
  5. Crashes into wall.

**Comment by amiller27** [comment]
That's very strange, it shouldn't change that at all.  I'm assuming the behavior is correct on master?

**Comment by ghost** [comment]
Nah, I only tested this :-). If it's nothing new, let's just merge this and make a separate issue.

**Comment by amiller27** [comment]
Everything works now, runs correctly with default directions of north and east, and doesn't do any extraneous pivot turns at the end

**Review by ghost — APPROVED** [review]

**Pull request merged**
