### PR TITLE
Cleanup orientation

### PR DESCRIPTION
**Pull request by amiller27**
I was super annoyed that this was being created on the heap, so it's not anymore.  Also the calibration now guarantees an uncertainty on the readings instead of just blindly taking a bunch of samples (another fix I found from a while ago that never got merged into master).  The calibration stuff was tested on the mouse back when I wrote it, the other stuff hasn't been.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
I won't be able to check it out in detail and test it until into this week. But right off the batt, I'll say:

 1. Not allocating it on the heap is awesome! Hooray for no more pointers and `->` all over the place.
 2. We should make a policy of what we do for logging. We don't have informational statements anywhere else in the code yet, so we should decide how to handle that first before adding them here. (e.g. Maybe we need multiple categories of logs that can be switched on and off individually)
 3. If we're going to use the Arduino F() macro, we should do it from inside LOG instead of at each use. (I think that will work, right?)

**Comment by amiller27** [comment]
Totally agree with 2, all of the ones that are there now were originally Serial writes, I just moved them to LOGs.  I do think we should have multiple categories, or possibly multiple debug levels (e.g. print out warnings of things that are probably bad or print out general information or print out so much debug info that the robot can't even drive itself properly).  Most big projects I've seen have debug levels like that.

About 3, if we put it inside the macro it means that passing something that's not a literal to LOG will pass something that's not a literal on to F.  I tried compiling code that does this, and it compiles fine.  I'm guessing it won't actually work, but I can't find the source for the __FlashStringHelper class that F is based on and I haven't tested it on an actual teensy.

**Comment by amiller27** [comment]
I'll get rid of the `F`'s, looks like teensy3 just treats them like normal `const char*`s

**Comment by ghost** [comment]
Yeah that's my bad, the log statements were already there. I still like the multiple categories or debug levels, but given what we're proposing, it should probably be handled as a separate item.

**Comment by ghost** [comment]
Tested on the robot through some RUNs and KAOSes. No different behavior observed.

Is there anything else we need to test?

**Comment by amiller27** [comment]
Nope, that's it

**Review by ghost — APPROVED** [review]

**Pull request merged**
