### PR TITLE
Kaos ends early AGAIN

### PR DESCRIPTION
**Pull request by awglyde**
Ryan found another use case where the micromouse stops a move early. Fixed by detecting a straight away like in pull request #120.

### CODE REVIEW

**Comment by awglyde** [comment]
@BishopofWales modified **buildRelativePath** so he should also be apart of discussions here.

**Comment by ghost** [comment]
Tested on the bot in the zig zag case, and in a few other random cases for sanity checking.

**Review by ghost — APPROVED** [review]
In the future, make a point of not including the bak files in your commits. The final diff is fine, but having intermediate commits that add and remove bak files is a little confusing.

Otherwise good to go.

**Comment by awglyde** [comment]
Will definitely avoid bak files in the future. That's what I get for using a new diffing tool.

**Pull request merged**
